name: cal_burner
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependency_overrides:
  health: ^11.1.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.3.0
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  icons_plus: ^5.0.0
  fl_chart: ^0.68.0
  percent_indicator: ^4.2.1
  shared_preferences: ^2.2.2
  pedometer: ^4.0.2
  permission_handler: ^11.3.1
  intl: ^0.19.0
  provider: ^6.1.1
  easy_localization: ^3.0.3
  image_picker: ^1.1.2
  flutter_local_notifications: ^19.2.1
  workmanager: ^0.6.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

#flutter_intl:   # dart run intl_utils:generate
flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
#
#  # App Icon Configuration    dart run flutter_launcher_icons:generate -o
#flutter_launcher_icons:
#  android: "assets/icons/app_logo.jpg"
#
#  ios: true
#  image_path: "assets/icons/app_logo.jpg"
#  min_sdk_android: 21
#  #  remove_alpha_ios: true
#  web:
#    generate: false

# Splash Screen Configuration   dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icons/cal_burnner.png
  color_dark: "#121212"
  image_dark: assets/icons/cal_burnner.png

  android_12:
    image: assets/icons/cal_burnner.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/icons/cal_burnner.png
    icon_background_color_dark: "#121212"

  web: false
  ios: false
  android: false

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/svg/
    - assets/translations/
  #   - images/a_dot_ham.jpeg


